apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: devops-exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: writer
          image: aapolaivm/log-output:v4.12
          command: [ "python", "/app/writer.py" ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: reader
          image: aapolaivm/log-output:v4.12
          command: [ "python", "/app/reader.py" ]
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"