apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: devops-exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: writer
          image: aapolaivm/log-output:v5.0
          command: [ "python", "/app/writer.py" ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/information.txt
              subPath: information.txt
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
        - name: reader
          image: aapolaivm/log-output:v5.0
          command: [ "python", "/app/reader.py" ]
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/information.txt
              subPath: information.txt
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
      volumes:
        - name: config-volume
          configMap:
            name: log-output-configmap