apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
  namespace: devops-exercises
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-output-svc   # Pointing to the log-output service
            port:
              number: 3000
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: pingpong-svc     # Pointing to the pingpong service
            port:
              number: 5001
    