apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: devops-exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: aapolaivm/pingpong:v3.0
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pingpong-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pingpong-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pingpong-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: postgres-svc.devops-exercises.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"