apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: devops-exercises
spec:
  selector:
    app: pingpong
  type: NodePort
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
