apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/namespace.yaml
  - manifests/postgres-secret.yaml
  - manifests/postgres-service.yaml

images:
  - name: PROJECT/IMAGE
    newName: gcr.io/dwk-gke-449420/todo-backend
    newTag: $BRANCH-$GITHUB_SHA