apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project-namespace
spec:
  strategy:
    type: Recreate  
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: aapolaivm/todo-app:v1.3
        ports: 
        - containerPort: 8080
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        volumeMounts:
        - mountPath: /mnt/data/image-cache
          name: image-cache
      volumes:
      - name: image-cache
        persistentVolumeClaim:
          claimName: image-cache-pvc
        
        