apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ing
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-app-svc
            port:
              number: 8080