apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-cache-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  gcePersistentDisk:
    pdName: image-cache-disk
    fsType: ext4
