apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-cache-pvc
  namespace: project-namespace
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
