apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: loki-stack
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.loki-stack.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: project-namespace
        pipeline_stages:
          - docker: {}
        static_configs:
          - targets: ['localhost']
            labels:
              job: kubernetes-pods
              __path__: /var/log/pods/*/*/*.log
